# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: osx-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/osx-64/_pytorch_select-0.1-cpu_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/blas-1.0-mkl.conda
https://conda.anaconda.org/conda-forge/osx-64/c-ares-1.17.1-h0d85af4_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ca-certificates-2021.4.13-hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/intel-openmp-2019.4-233.conda
https://conda.anaconda.org/conda-forge/osx-64/jpeg-9d-hbcb3906_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcxx-11.1.0-habf9029_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libev-4.33-haf1e3a3_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libsodium-1.0.18-h1de35cc_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libwebp-base-1.2.0-h0d85af4_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/llvm-openmp-11.1.0-hda6cdc1_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mkl-include-2020.4-h08c4f10_301.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pandoc-2.12-hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/xz-5.2.5-h1de35cc_0.conda
https://conda.anaconda.org/conda-forge/osx-64/yaml-0.2.5-haf1e3a3_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/zlib-1.2.11-h1de35cc_3.conda
https://repo.anaconda.com/pkgs/main/osx-64/libffi-3.3-hb1e8313_2.conda
https://conda.anaconda.org/conda-forge/osx-64/libgfortran5-9.3.0-h6c81a4c_21.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/libmklml-2019.0.5-0.conda
https://repo.anaconda.com/pkgs/main/osx-64/libpng-1.6.37-ha441bb4_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libprotobuf-3.15.6-hcf210ce_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/lz4-c-1.9.3-h046ec9c_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mkl-2020.4-h08c4f10_301.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ncurses-6.2-h0a44026_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/ninja-1.10.2-hf7b0b51_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/openssl-1.1.1k-h9ed2024_0.conda
https://conda.anaconda.org/conda-forge/osx-64/sleef-3.5.1-h35c211d_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/tk-8.6.10-hb0a8c7a_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/zeromq-4.3.4-h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/freetype-2.10.4-ha233b18_0.conda
https://conda.anaconda.org/conda-forge/osx-64/libblas-3.9.0-8_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libedit-3.1.20191231-h0678c8f_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libgfortran-5.0.0-9_3_0_h6c81a4c_21.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libnghttp2-1.43.0-h07e645a_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libssh2-1.9.0-h52ee1ee_6.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/mkl-devel-2020.4-h694c41f_302.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/readline-8.1-h9ed2024_0.conda
https://conda.anaconda.org/conda-forge/osx-64/zstd-1.4.9-h582d3a0_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/krb5-1.17.2-h60d9502_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcblas-3.9.0-8_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapack-3.9.0-8_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libtiff-4.2.0-h355d032_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/sqlite-3.35.4-hce871da_0.conda
https://conda.anaconda.org/conda-forge/osx-64/lcms2-2.12-h577c468_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/libcurl-7.75.0-h8ef9fac_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/liblapacke-3.9.0-8_mkl.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/python-3.8.8-h88f2d9e_5.conda
https://repo.anaconda.com/pkgs/main/osx-64/appnope-0.1.2-py38hecd8cb5_1001.conda
https://conda.anaconda.org/conda-forge/noarch/async-timeout-3.0.1-py_1000.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/async_generator-1.10-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/attrs-20.3.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/backcall-0.2.0-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports-1.0-py_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/blas-devel-3.9.0-8_mkl.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/blinker-1.4-py_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cached_property-1.5.2-pyha770c72_1.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cachetools-4.2.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/certifi-2020.12.5-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/click-7.1.2-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/decorator-5.0.6-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/defusedxml-0.7.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/entrypoints-0.3-py38_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/fastcache-1.1.0-py38h1de35cc_0.conda
https://conda.anaconda.org/conda-forge/osx-64/hdf5-1.10.6-nompi_hc5d9132_1114.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/idna-2.10-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/ipython_genutils-0.2.0-pyhd3eb1b0_1.conda
https://conda.anaconda.org/conda-forge/noarch/json5-0.9.5-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/kiwisolver-1.3.1-py38h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/markupsafe-1.1.1-py38h1de35cc_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/mistune-0.8.4-py38h1de35cc_1001.conda
https://conda.anaconda.org/conda-forge/noarch/nest-asyncio-1.4.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/olefile-0.46-pyh9f0ad1d_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pandocfilters-1.4.3-py38hecd8cb5_1.conda
https://repo.anaconda.com/pkgs/main/noarch/parso-0.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pickleshare-0.7.5-pyhd3eb1b0_1003.conda
https://repo.anaconda.com/pkgs/main/noarch/prometheus_client-0.10.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/ptyprocess-0.7.0-pyhd3eb1b0_2.conda
https://conda.anaconda.org/conda-forge/noarch/pyasn1-0.4.8-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pycparser-2.20-py_2.conda
https://conda.anaconda.org/conda-forge/noarch/pyjwt-2.0.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pyparsing-2.4.7-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pyrsistent-0.17.3-py38haf1e3a3_0.conda
https://conda.anaconda.org/conda-forge/noarch/python-flatbuffers-1.12-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/python_abi-3.8-1_cp38.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pytz-2021.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pyzmq-20.0.0-py38h23ab428_1.conda
https://repo.anaconda.com/pkgs/main/noarch/send2trash-1.5.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/osx-64/six-1.15.0-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/tabulate-0.8.9-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/tensorboard-plugin-wit-1.8.0-pyh44b312d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/testpath-0.4.4-pyhd3eb1b0_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.1.0-pyh5ca1d4c_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/tornado-6.1-py38h9ed2024_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tqdm-4.59.0-pyhd3eb1b0_1.conda
https://conda.anaconda.org/conda-forge/noarch/typing_extensions-3.7.4.3-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wcwidth-0.2.5-py_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/webencodings-0.5.1-py38_1.conda
https://conda.anaconda.org/conda-forge/noarch/werkzeug-1.0.1-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/wheel-0.36.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/zipp-3.4.1-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/absl-py-0.12.0-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/babel-2.9.0-pyhd3deb0d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/cached-property-1.5.2-hd8ed1ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cffi-1.14.5-py38h2125817_0.conda
https://conda.anaconda.org/conda-forge/osx-64/chardet-4.0.0-py38h50d1736_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/cycler-0.10.0-py38_0.conda
https://conda.anaconda.org/conda-forge/osx-64/future-0.18.2-py38h50d1736_3.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/importlib-metadata-3.10.0-py38hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/jedi-0.17.0-py38_0.conda
https://conda.anaconda.org/conda-forge/osx-64/mkl-service-2.3.0-py38h4d0b108_2.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/multidict-5.1.0-py38h5406a74_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/numpy-1.20.2-py38had91d27_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/packaging-20.9-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/pexpect-4.8.0-pyhd3eb1b0_3.conda
https://conda.anaconda.org/conda-forge/osx-64/pillow-8.1.2-py38h83525de_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/prompt-toolkit-3.0.17-pyh06a4308_0.conda
https://conda.anaconda.org/conda-forge/noarch/pyasn1-modules-0.2.7-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pysocks-1.7.1-py38h50d1736_3.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.1-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/pyyaml-5.4.1-py38h5406a74_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/rsa-4.7.2-pyh44b312d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/setuptools-52.0.0-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/sniffio-1.2.0-py38h50d1736_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/terminado-0.9.4-py38hecd8cb5_0.conda
https://repo.anaconda.com/pkgs/main/noarch/traitlets-5.0.5-pyhd3eb1b0_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/typing-extensions-3.7.4.3-0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/anyio-2.2.0-py38h50d1736_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/argon2-cffi-20.1.0-py38h5406a74_2.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/backports.functools_lru_cache-1.6.3-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/bleach-3.3.0-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/brotlipy-0.7.0-py38h5406a74_1001.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/cryptography-3.4.7-py38h1fa4640_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/grpcio-1.36.1-py38ha263829_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/h5py-2.10.0-py38h0601b69_1.conda
https://repo.anaconda.com/pkgs/main/noarch/importlib_metadata-3.10.0-hd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/jinja2-2.11.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/noarch/joblib-1.0.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyter-packaging-0.7.12-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/jupyter_core-4.7.1-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/markdown-3.3.4-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-base-3.3.4-py38h8b3ea08_0.conda
https://repo.anaconda.com/pkgs/main/noarch/opt_einsum-3.1.0-py_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/pandas-1.2.4-py38h23ab428_0.conda
https://repo.anaconda.com/pkgs/main/osx-64/pip-21.0.1-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/osx-64/protobuf-3.15.6-py38ha048514_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/pygments-2.8.1-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/pytorch-1.8.0-cpu_py38h9037c18_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/scipy-1.6.2-py38h431c0a8_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/yarl-1.6.3-py38h5406a74_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/aiohttp-3.7.4-py38h96a0964_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ipython-7.22.0-py38h01d92e1_0.conda
https://conda.anaconda.org/conda-forge/osx-64/jaxlib-0.1.64-py38h50d1736_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/jsonschema-3.2.0-py_2.conda
https://repo.anaconda.com/pkgs/main/noarch/jupyter_client-6.1.12-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_pygments-0.1.2-pyh9f0ad1d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/matplotlib-3.3.4-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/oauthlib-3.0.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/patsy-0.5.1-py_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/pyopenssl-20.0.1-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/scikit-learn-0.24.1-py38hb2f4e1b_0.conda
https://conda.anaconda.org/conda-forge/noarch/seaborn-base-0.11.1-pyhd8ed1ab_1.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/tensorboard-1.15.0-py38_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-auth-1.26.1-pyh44b312d_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/ipykernel-5.3.4-py38h5ca1d4c_0.conda
https://conda.anaconda.org/conda-forge/noarch/jax-0.2.11-pyhd8ed1ab_0.tar.bz2
https://repo.anaconda.com/pkgs/main/noarch/nbformat-5.1.3-pyhd3eb1b0_0.conda
https://conda.anaconda.org/conda-forge/osx-64/statsmodels-0.12.2-py38ha1b04c9_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/urllib3-1.26.4-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbclient-0.5.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/requests-2.25.1-pyhd3deb0d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/seaborn-0.11.1-hd8ed1ab_1.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/nbconvert-6.0.7-py38_0.conda
https://conda.anaconda.org/conda-forge/noarch/requests-oauthlib-1.3.0-pyh9f0ad1d_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/google-auth-oauthlib-0.4.3-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/osx-64/jupyter_server-1.5.1-py38h50d1736_0.tar.bz2
https://repo.anaconda.com/pkgs/main/osx-64/notebook-6.3.0-py38hecd8cb5_0.conda
https://conda.anaconda.org/conda-forge/noarch/jupyterlab_server-2.3.0-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/nbclassic-0.2.6-pyhd8ed1ab_0.tar.bz2
https://conda.anaconda.org/conda-forge/noarch/jupyterlab-3.0.12-pyhd8ed1ab_0.tar.bz2
