dataset:
  args:
    root: data/
    train: true
  type: RQP4
model:
  args:
    hid_features:
    - 32
  type: MahalanobisAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 100
    checkpoint_start: 200
    max_epochs: 800
    shuffle: true
    tb_logs:
    - - plot_reconstruction
      - {}
    - - plot_slow_latent_correlation
      - {}
    valid_split: 0.3
  type: SimpleTrainer
