dataset:
  args:
    root: data/
    train: true
  type: RQP4
loss_func:
  args: {}
  type: MahalanobisLoss
model:
  args:
    hidden_features:
    - 16
    - 16
  type: SimpleAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.0001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 50
    checkpoint_start: 50
    max_epochs: 200
    shuffle: true
    valid_split: 0.3
  type: MMSELossTrainer
