dataset:
  args:
    root: data/
    train: true
  type: RQP4
model:
  args:
    hidden_features:
    - 32
    - 16
    l1_weight: 1.5
    mah_weight: 0.9
  type: MahalanobisL1Autoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 100
    checkpoint_start: 100
    max_epochs: 1000
    shuffle: true
    valid_split: 0.3
  type: SimpleTrainer
