dataset:
  args:
    root: data/
    train: true
  type: RQP4
loss_function:
  args: {}
  type: MSELoss
network:
  args:
    hidden_features:
    - 8
    - 4
  type: SimpleAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 50
    checkpoint_start: 50
    max_epochs: 500
    shuffle: true
    valid_split: 0.3
  type: SimpleLossTrainer
