dataset:
  args:
    root: data/
    train: true
  type: RQP4
model:
  args:
    hidden_features:
    - 8
    - 4
  type: SemiMahalanobisAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 100
    checkpoint_start: 100
    max_epochs: 500
    shuffle: true
    valid_split: 0.3
  type: SimpleTrainer
