dataset:
  args:
    generate: false
    root: data/
    train: true
  type: RQP4
loss_func:
  args: {}
  type: L1Loss
model:
  args:
    hidden_features:
    - 12
    - 4
  type: SimpleAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    burst_dt: 0.004
    burst_size: 10000
    checkpoint_freq: 50
    checkpoint_start: 50
    max_epochs: 250
    shuffle: true
    valid_split: 0.3
  type: SimpleLossTrainer
