dataset:
  args:
    generate: false
    root: data/
    train: true
  type: Quad4
model:
  args:
    hid_activ: ELU
    hid_features:
    - 16
    proj_loss: L1Loss
    proj_loss_wght: 0.7
  type: MahalanobisAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 300
    checkpoint_start: 100
    max_epochs: 2000
    shuffle: true
    tb_logs:
    - - plot_reconstruction
      - coords_labels:
        - x1
        - x2
    - - plot_slow_latent_correlation
      - {}
    valid_split: 0.3
  type: SimpleTrainer
