dataset:
  type: Quad4
  args:
    generate: false
    root: data/
    train: true

model:
  type: CoderNet
  args:
    hid_activ: ELU
    loss_func: MSELoss

optimizer:
  type: Adam
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0

trainer:
  type: SimpleTrainer
  args:
    batch_size: 16
    checkpoint_freq: 300
    checkpoint_start: 100
    max_epochs: 2000
    shuffle: true
    tb_logs:
    - - plot_reconstruction
      - {}
    - - plot_slow_latent_correlation
      - {}
    valid_split: 0.3
