dataset:
  args:
    generate: false
    root: data/
    train: true
  type: Quad10
model:
  args:
    hid_activ: ELU
    hid_features:
    - 6
    - 4
    proj_loss: L1Loss
    proj_loss_wght: 1.0
  type: MahalanobisAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 300
    checkpoint_start: 100
    max_epochs: 3000
    shuffle: true
    tb_logs:
    - - plot_reconstruction
      - coords:
        - 0
        - 2
        coords_labels:
        - x1
        - x3
    - - plot_reconstruction
      - coords:
        - 1
        - 3
        coords_labels:
        - x2
        - x4
    - - plot_slow_latent_correlation
      - coord: 0
    - - plot_slow_latent_correlation
      - coord: 1
    valid_split: 0.3
  type: SimpleTrainer
