dataset:
  args:
    generate: false
    root: data/
    train: true
  type: Quad10

model:
  type: CoderNet
  args:
    hid_activ: ELU
    hid_features:
    - 10
    - 5
    loss_func: MSELoss
    inp_bias: False

optimizer:
  type: Adam
  args:
    amsgrad: true
    lr: 0.003
    weight_decay: 0

trainer:
  type: PrunedTrainer
  args:
    batch_size: 16
    checkpoint_freq: 300
    checkpoint_start: 100
    max_epochs: 4500
    shuffle: true
    tb_logs:
    - - plot_reconstruction
      - coords:
        - 0
        - 2
        coords_labels:
        - x1
        - x3
    - - plot_reconstruction
      - coords:
        - 1
        - 3
        coords_labels:
        - x2
        - x4
    - - plot_slow_latent_correlation
      - coord: 0
    - - plot_slow_latent_correlation
      - coord: 1
    valid_split: 0.3
    pruning:
      type: global_unstructured
      target_sparsity: 0.3
      args:
        pruning_method: L1Unstructured
        amount: 0.03
        parameters:
        - encoder.layer1.weight
        - encoder.layer2.weight
        - encoder.layer2.bias
        - decoder.layer1.weight
        - decoder.layer1.bias
        - decoder.layer2.weight
        - decoder.layer2.bias
      schedule:
      - 100
      - 150
