dataset:
  type: Quad10
  args:
    generate: false
    root: data/
    train: true

model:
  type: CoderNet
  args:
    hid_activ: ELU
    hid_features:
    - 12
    - 8
    - 4
    loss_func: MSELoss

optimizer:
  type: Adam
  args:
    amsgrad: true
    lr: 0.002
    weight_decay: 0

trainer:
  type: SimpleTrainer
  args:
    batch_size: 16
    checkpoint_freq: 300
    checkpoint_start: 100
    max_epochs: 3000
    valid_split: 0.3
    shuffle: true
    tb_logs:
    - - plot_reconstruction
      - coords:
        - 0
        - 2
        coords_labels:
        - x1
        - x3
    - - plot_reconstruction
      - coords:
        - 1
        - 3
        coords_labels:
        - x2
        - x4
    - - plot_slow_latent_correlation
      - coord: 0
    - - plot_slow_latent_correlation
      - coord: 1
