dataset:
  args:
    root: data/
    train: true
  type: Sin2
model:
  args:
    hid_activ: Tanh
    hid_features:
    - 4
    - 4
  type: MahalanobisAutoencoder
optimizer:
  args:
    amsgrad: true
    lr: 0.001
    weight_decay: 0
  type: Adam
trainer:
  args:
    batch_size: 16
    checkpoint_freq: 300
    checkpoint_start: 100
    max_epochs: 5000
    shuffle: true
    tb_logs:
    - - plot_reconstruction
      - {}
    - - plot_slow_latent_correlation
      - {}
    valid_split: 0.3
  type: SimpleTrainer
