dataset:
  type: Sin2
  args:
    root: data/
    train: True

model:
  type: MahalanobisAutoencoder
  args:
    hid_features:
      - 4
    hid_activ: ELU
    proj_loss: MSELoss
    proj_loss_wght: 0.7
    normalize_precs: True

optimizer:
  type: Adam
  args:
    lr: 0.002
    weight_decay: 0
    amsgrad: True

trainer:
  type: SimpleTrainer
  args:
    max_epochs: 2000

    checkpoint_start: 100
    checkpoint_freq: 300
    tb_logs:
      - [plot_reconstruction, {}]

    batch_size: 16
    shuffle: True
    valid_split: 0.3
