dataset:
  type: Sin2
  args:
    root: data/
    train: True

model:
  type: CoderNet
  args:
    hid_features:
      - 3
    hid_activ: ELU
    loss_func: MSELoss

optimizer:
  type: Adam
  args:
    lr: 0.003
    weight_decay: 0
    amsgrad: True

trainer:
  type: SimpleTrainer
  args:
    max_epochs: 1500

    checkpoint_start: 100
    checkpoint_freq: 300
    tb_logs:
      - [plot_reconstruction, {}]

    batch_size: 16
    shuffle: True
    valid_split: 0.3
